
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - uses: actions/checkout@v2

      - run: make run

      - name: Commit built branch
        run: |
          set +e
          git config user.name github-actions
          git config user.email github-actions@github.com
          cp -R build /tmp/build
          git fetch
          git branch -a
          git checkout -f -b built origin/built
          rm -rf ./*
          cp -R /tmp/build/* .
          git status
          git add .
          git commit -m "built"
          git push origin built
